name: Python package

on:
  pull_request:
    branches:
    - master

jobs:
  format_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install black and mypy
      run: |
        python -m pip install --upgrade pip
        pip install black
        pip install mypy
        pip install .
    - name: Format and test
      run: |
        python -m black --check -l 100 -t py36 -S .
        mypy mypy_tests/
