name: Black and flake8

on:
  pull_request:
    branches:
    - master

jobs:
  format_code:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install black
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 flake8-pyi
    - name: Generate pyi files
      run: |
        python gen_pyi.py
    - name: Format with black
      run: |
        python -m black --check -l 100 -t py36 .
    - name: Lint with flake8
      run: |
        flake8 *-stubs
