name: flake8

on:
  pull_request:
    branches:
    - master

jobs:
  lint_code:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-pyi
    - name: Lint with flake8
      run: |
        flake8 *-stubs
