name: Mypy

on:
  pull_request:
    branches:
    - master

jobs:
  check_with_mypy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install mypy
      run: |
        python -m pip install --upgrade pip
        pip install mypy==0.770
        pip install .
    - name: Check with mypy
      run: |
        mypy tests/
