name: UploadRelease

on:
  create:
    tags:
      - 'v*'
    branches-ignore:
      - '*'

jobs:
  upload_release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install twine
      run: |
        python -m pip install --upgrade pip
        pip install setuptools twine wheel
    - name: Build package
      run: |
        python setup.py sdist bdist_wheel
    - name: Upload to pypi
      run: |
        cat >> ~/.pypirc << EOM
        [distutils]
        index-servers = 
          pypi

        [pypi]
        repository: https://upload.pypi.org/legacy/
        username: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_PASSWORD }}
        EOM

        twine upload dist/*
