name: Pytest

on:
  pull_request:
    branches:
    - master

jobs:
  format_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pytest and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest numpy pandas matplotlib
    - name: Format and test
      run: |
        python -m pytest -vv tests/
